# Generated by Django 4.1.7 on 2023-03-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='food_pref',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
