# Generated by Django 4.0.3 on 2023-04-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_packingtodolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackingTodoList',
        ),
    ]
