# Generated by Django 4.2.6 on 2023-10-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CW", "Content Writer"),
                    ("FN", "Finance"),
                    ("MK", "Marketing"),
                    ("DS", "Design"),
                    ("DV", "Developer"),
                    ("BK", "Banking"),
                    ("VE", "Video Editor/Reel Creator"),
                    ("SM", "Social Media"),
                    ("SE", "SEO"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(blank=True, to="accounts.skill"),
        ),
    ]
