# Generated by Django 4.2.6 on 2023-10-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_skill_user_job_type_user_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="skills",
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
