# Generated by Django 4.2.6 on 2023-10-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_user_skills_user_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="job_type",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
