# Generated by Django 4.1.7 on 2023-03-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0002_rename_location_tripdetail_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
