# Generated by Django 4.1.7 on 2023-03-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0003_tripdetail_end_date_tripdetail_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
