# Generated by Django 4.2.6 on 2023-10-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_rename_location_community_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name="project",
            name="skills_used",
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
